import { StyleSheet } from "react-native";
import colors from "../../../constants/colors";
import {
  moderateScale,
  scale,
  textScale,
  verticalScale,
} from "../../../constants/responsiveSizes";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    position: "absolute",
    top: 0,
    paddingTop: verticalScale(35),
    paddingBottom: verticalScale(25),
    paddingHorizontal: scale(16),
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  headerAgain: {
    position: "absolute",
    top: 0,
    paddingTop: verticalScale(35),
    paddingBottom: verticalScale(25),
    paddingHorizontal: scale(16),
    width: "100%",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
  },
  menuIcon: {
    height: moderateScale(24),
    width: moderateScale(24),
    top: verticalScale(20),
  },
  headerText: {
    fontSize: textScale(24),
    fontFamily: "C-Regular",
    fontWeight: "700",
    color: colors.black,
    textAlign: "center",
    top: verticalScale(20),
  },
  headerText2: {
    fontSize: textScale(14),
    fontFamily: "C-Regular",
    fontWeight: "700",
    color: colors.black,
    textAlign: "center",
    top: verticalScale(20),
  },
  footer: {
    height: moderateScale(95),
    backgroundColor: colors.white,
    borderRadius: moderateScale(40),
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    marginHorizontal: moderateScale(16),
    backgroundColor: colors.white,
    marginTop: verticalScale(10),
  },

  tabText: {
    fontSize: textScale(10),
    fontWeight: "600",
    fontFamily: "C-Regular",
    paddingTop: moderateScale(4),
  },
  tabIcon: {
    width: moderateScale(40),
    height: moderateScale(40),
  },
  searchBarCont: {
    position: "absolute",
    top: moderateScale(120),
    width: "100%",
    flexDirection: "row",
    paddingHorizontal: scale(16),
  },
  filterCont: {
    height: moderateScale(40),
    width: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    marginTop: verticalScale(3),
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: moderateScale(4),
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  filterIcon: {
    width: moderateScale(20),
    height: moderateScale(20),
  },
  showEventsCont: {
    position: "absolute",
    bottom: verticalScale(120),
    paddingHorizontal: scale(16),
    backgroundColor: colors.grey,
    height: moderateScale(49),
    width: moderateScale(49),
    right: scale(16),
    borderRadius: moderateScale(24.5),
    justifyContent: "center",
    alignItems: "center",
  },
  rectangle: {
    width: moderateScale(28),
    height: moderateScale(28),
    borderRadius: moderateScale(5),
    backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
  },

  selectText: {
    fontSize: textScale(20),
    fontFamily: "C-Bold",
    color: colors.black,
    fontWeight: "bold",
    paddingTop: verticalScale(10),
    paddingBottom: verticalScale(10),
  },
  filterLayout: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: scale(16),
  },
  nameCont: {
    height: moderateScale(30),
    paddingHorizontal: moderateScale(10),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: moderateScale(15),
    borderWidth: 1,
    borderColor: colors.borderColor,
    marginTop: verticalScale(10),
    marginRight: scale(10),
    flexDirection: "row",
  },
  selectedArtist: {
    backgroundColor: colors.logoColor,
  },
  artistText: {
    fontSize: textScale(12),
    fontWeight: "400",
    color: colors.black,
  },
  selectedArtistText: {
    color: colors.white,
  },
  heading: {
    fontFamily: "C-Bold",
    fontSize: textScale(20),
    fontWeight: "bold",
    marginTop: moderateScale(20),
  },
  mainCont: {
    paddingHorizontal: scale(16),
  },
  showAllButton: {
    height: moderateScale(30),
    width: moderateScale(30),
    borderRadius: moderateScale(15),
    backgroundColor: colors.logoColor,
    justifyContent: "center",
    alignItems: "center",
    marginTop: verticalScale(10),
    marginLeft: scale(5),
  },
  showAllText: {
    color: colors.white,
    fontSize: textScale(12),
    fontWeight: "400",
    fontFamily: "C-Regular",
  },
});

export default styles;
